### ISSUE TITLE
Use import matplotlib.pylab instead of import pylab

### ISSUE THREAD

**Issue by kubark42** [dronecrew/px4tools#3]
http://stackoverflow.com/questions/32279887/pylab-module-object-has-no-attribute-figure

I was initially unable to use px4tools because the `pl` namespace was empty, _a la_ http://stackoverflow.com/questions/30880407/pylab-does-not-have-any-attrs/30880734. 

This doesn't seem to be a universally solvable problem, so the general consensus I saw via google is to use `import matplotlib.pylab as pl` instead of `import pylab as pl`. I worked around this with the upstream px4tools code by having to `pip uninstall` both `pylab` and `matplotlib`, and then `pip install matplotlib`.

If this is a useful change, it might be helpful to update https://github.com/jgoppert/lpe-analysis/blob/master/15-09-30%20Kabir%20Log.ipynb at the same time.

**Comment by jgoppert** [comment]
I never install the pylab package, I always just install the matplotlib package, does it work if you do this. You can still import using pylab then I believe.

**Comment by jgoppert** [comment]
Fixed this now.
