### ISSUE TITLE
ValueError: 'timestamp' is both an index level and a column label, which is ambiguous.

### ISSUE THREAD

**Issue by w407022008** [dronecrew/px4tools#40]
Hello, 

When i run those codes in Jupyter Notebook from [here](https://github.com/dronecrew/px4tools/blob/master/examples/ulog%20analysis.ipynb):
`d_concat = d.concat(dt=0.01)`
`d_concat_computed = px4tools.compute_data(d_concat) `
`px4tools.estimator_analysis(d_concat_computed)`

It show me the following error:
> ValueError                                Traceback (most recent call last)
> <ipython-input-17-cf7a11cdff79> in <module>
> ----> 1 d_concat = d.concat(dt=0.01)
>       2 d_concat_computed = px4tools.compute_data(d_concat)
>       3 px4tools.estimator_analysis(d_concat_computed)
> 
> ~\anaconda3\lib\site-packages\px4tools\ulog.py in concat(self, topics, on, dt, verbose)
>     651                 print('merging {:s} as of timestamp'.format(topic))
>     652             df = d[topic]
> --> 653             df.sort_values(by='timestamp', inplace=True)
>     654             m = pd.merge_asof(m, df, 'timestamp')
>     655         m.index = pd.TimedeltaIndex(m.timestamp * 1e3, unit='ns')
> 
> ~\anaconda3\lib\site-packages\pandas\core\frame.py in sort_values(self, by, axis, ascending, inplace, kind, na_position, ignore_index)
>    4925 
>    4926             by = by[0]
> -> 4927             k = self._get_label_or_level_values(by, axis=axis)
>    4928 
>    4929             if isinstance(ascending, (tuple, list)):
> 
> ~\anaconda3\lib\site-packages\pandas\core\generic.py in _get_label_or_level_values(self, key, axis)
>    1685 
>    1686         if self._is_label_reference(key, axis=axis):
> -> 1687             self._check_label_or_level_ambiguity(key, axis=axis)
>    1688             values = self.xs(key, axis=other_axes[0])._values
>    1689         elif self._is_level_reference(key, axis=axis):
> 
> ~\anaconda3\lib\site-packages\pandas\core\generic.py in _check_label_or_level_ambiguity(self, key, axis)
>    1645                 f"{label_article} {label_type} label, which is ambiguous."
>    1646             )
> -> 1647             raise ValueError(msg)
>    1648 
>    1649     def _get_label_or_level_values(self, key: str, axis: int = 0) -> np.ndarray:
> 
> ValueError: 'timestamp' is both an index level and a column label, which is ambiguous.

Does anyone know What’s the problem? 

Thx a lot.

**Comment by tomcattigerkkk** [comment]
@w407022008  The problem is that both index and column have 'timestamp'. My solution is to clone the code and add 
df.index.rename('time_stamp', inplace=True)
after line 652 df = d[topic] in ulog.py. 
After that, I've used python setup.py install to install the local version
I'm not sure if it has a bad influence on handing the data.
